// <auto-generated />
namespace PFSheets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addlevels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlevels));
        
        string IMigrationMetadata.Id
        {
            get { return "201502162158506_add-levels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
